Fix venv setup broken by modern virtualenv on Python 3.7
Fixes:

    test -d env || virtualenv --pip 23.2 --setuptools 60.1.0 --wheel 0.37.1 -p /usr/bin/python3.7 env
    RuntimeError: failed to query /usr/bin/python3.7 with code 1 err: '  File "/usr/lib/python3.14/site-packages/python_discovery/_py_info.py", line 183\n    if (tk_lib := tcl.eval("set tk_library")) and os.path.isdir(tk_lib):\n               ^\nSyntaxError: invalid syntax\n'
    make: *** [Makefile:81: env/bin/activate] Error 1